Revise paperless-ngx backup process: - Must detect when file detected

diff --git a/Home-Server-Setup/ansible/roles/deploy-paperless-ngx/templates/paperless_ngx-backup.sh.j2 b/Home-Server-Setup/ansible/roles/deploy-paperless-ngx/templates/paperless_ngx-backup.sh.j2
--- a/Home-Server-Setup/ansible/roles/deploy-paperless-ngx/templates/paperless_ngx-backup.sh.j2
+++ b/Home-Server-Setup/ansible/roles/deploy-paperless-ngx/templates/paperless_ngx-backup.sh.j2
@@ -2,8 +2,30 @@
 
 ### {{ ansible_managed }}
 
+EXPORT_DIRECTORY="{{ paperless_ngx_backup_directory }}"
+PAPERLESS_EXPORT_FILENAME="{{ paperless_ngx_nfs_backup_script_paperless_export_filename }}"
+FULL_PATH_BACKUP="$EXPORT_DIRECTORY/$PAPERLESS_EXPORT_FILENAME"
+COUNTER=0
+MAX_ATTEMPTS={{ paperless_ngx_nfs_backup_script_max_attempts }}
+BACKUP_CHECK_INTERVAL={{ paperless_ngx_nfs_backup_script_backup_check_interval }}
+
 docker exec -d {{ paperless_ngx_container_name }} document_exporter ../export -d -f -p -sm -z --no-progress-bar
 
-sleep 5s && rsync --remove-source-files -zv {{ paperless_ngx_backup_directory }}/*.zip {{ paperless_ngx_nfs_backup_directory }}
+while [ ! -f "$FULL_PATH_BACKUP" ]; do
+    echo "Waiting for $FULL_PATH_BACKUP to be created..."
+    COUNTER=$((COUNTER + 1))  # Increment the counter
+    echo "Backup Attempt Number: $COUNTER"
+    sleep $BACKUP_CHECK_INTERVAL  # Wait for 5 seconds before checking again
 
+    # Exit if max attempts reached
+    if [ "$COUNTER" -ge "$MAX_ATTEMPTS" ]; then
+        echo "File $FULL_PATH_BACKUP not found after $MAX_ATTEMPTS attempts. Exiting."
+        exit 1  # Exit with an error code
+    fi
+done
+
+echo "$FULL_PATH_BACKUP exists! Continuing with the script..."
+# Need to wait even after the backup file is detected
+# Paperless-ngx takes time to fully generate the export
+sleep 180s && rsync --remove-source-files -zv {{ paperless_ngx_backup_directory }}/*.zip {{ paperless_ngx_nfs_backup_directory }}
 find {{ paperless_ngx_nfs_backup_directory }} -mtime +{{ paperless_ngx_nfs_backup_cleanup_period }} -exec rm {} \;
